import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import HeroSection from "@/components/Home/HeroSection/HeroSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <div className="min-h-screen"> */}
      <body className={inter.className}>{children}</body>
      {/* </div> */}
    </html>
  );
}
